language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-21
    - android-27
script:
  - "gradle wrapper"
  - "./gradlew build"